---
format_version: 10
pipelines:
    java_microservice:
        group: micronservices
        lock_behaviour: unlockWhenFinished
        label_template: 
        materials:
            git_java_microservice:
                git: https://github.com/alevenciks/gcd_pipelines.git
                branch: main
                shallow_clone: true
                auto_update: true
        stages:
            - build:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: bash
                                arguments: 
                                    - c
                                    - echo "Building java app"
        